# Specify the node base image with your desired version, e.g. node:<version>
FROM postgres:latest

# Make the container accept traffic on port 3000 at runtime from other
# containers or the host if also published
EXPOSE 5432


